extends: airbnb
plugins:
  - import
rules:
  react/require-extension: off
  space-before-function-paren: off
  brace-style: [2, 'stroustrup']
  arrow-body-style: [1]
  react/prefer-stateless-function: [1]
  no-underscore-dangle: 1
env:
  browser: true
  node: true
  es6: true
